FROM node:20-alpine AS build
WORKDIR /app

COPY app/portal/package*.json ./
RUN npm ci

COPY app/portal ./

RUN npm run build

FROM node:20-alpine AS runtime
WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]