name: .NET CI with MySQL

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      ConnectionStrings__DefaultConnection: "server=127.0.0.1;port=3306;database=testdb;uid=testuser;pwd=testpass"
      ASPNETCORE_ENVIRONMENT: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 Preview
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100-preview.4.24266.19'

      - name: Install EF Core CLI tools
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore To-Do-List/To-Do-List.csproj

      - name: Build solution
        run: dotnet build To-Do-List/To-Do-List.csproj --configuration Release --no-restore

      - name: "Apply EF migration: MyIdentityDbContext"
        run: dotnet ef database update --context To_Do_List.Identity.DbContext.MyIdentityDbContext --project To-Do-List/To-Do-List.csproj --startup-project To-Do-List/To-Do-List.csproj

      - name: "Apply EF migration: TaskDbContext"
        run: dotnet ef database update --context To_Do_List.Tasks.DbContext.TaskDbContext --project To-Do-List/To-Do-List.csproj --startup-project To-Do-List/To-Do-List.csproj

      - name: "Apply EF migration: SystemConfigurationContext"
        run: dotnet ef database update --context To_Do_List.Configuration.DbContext.SystemConfigurationContext --project To-Do-List/To-Do-List.csproj --startup-project To-Do-List/To-Do-List.csproj

      - name: Run tests
        run: dotnet test To-Do-List/To-Do-List.csproj --configuration Release --no-build --verbosity normal
